language: python

addons:
  apt:
    packages:
    - mobile-broadband-provider-info

python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

install:
- pip install flake8

script:
- flake8 mkwvconf.py
- bash test.sh
