language: python

addons:
  apt:
    packages:
    - mobile-broadband-provider-info

python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

install:
- pip install flake8

script:
- flake8 mkwvconf.py
- bash test.sh

before_deploy:
- echo "${TRAVIS_TAG}" > version.txt

deploy:
  skip_cleanup: true
  provider: pypi
  on:
    tags: true
    repo: ascoderu/mkwvconf
    python: "3.6"
  user: ascoderu
  password:
    secure: IHrGSN9bYPALsHhmUNyoJ8zfWBB+B9j7/8/LVXOB/95kiyP01RdjofQClkGKMhNwA0sr42OeiLElwH9z4mQQulX4/zU/xiJxMZu2JB4lrEJAY2z6/ffmqxzi7Es/qwjGCpG4UTopTQzSUCU64zdFIHJ+ouagY9eRPy4fx0V33sfR1QBQCZKJVpmY9CQK9Ud9ebfZJ/71bUcIgYqM9fVgSycPQU34P3hgR9MELtvVbqU1UEQLvFcbHBbZ2LKecOcJDxpHzj7MLB4AH3FrafQ/PuQflj0OAhNUdjRiL4+1GoyJjEQWzGnVKORUyZeoDncS+EdqDGAJy5XvsatPKEzrM9BWgZmZorFcDix2BiidNifg5j6UxAQa8xWka/j6MFiWt8MmoDNla1vkEJi0PJyTdECQi5mysnYNgOPX5A3j39UjTNhXuqUUgEhF/Risn0pQGb5iUcHX46pcU3ppUev1Z6NDMR54YC3TWvKMpK7xDI61gbstaeTI6XZB9uXY1342nqf2kcsxuxaAmbF1wBS8LPT11sjkUtsDHo+4Wrk1SrK4Sruixvewe7XqkpLKTZR0VtktL6P+0jhdj+yBepLWMWYwYG/GwPRJuz0iKMalJFvRcHzf2hLNDCOEbW5t2l9YnPqZ88u64n7SGXejrDo2lFJFSp/ZvFh/yGAd29rDO78=
